### ISSUE TITLE
Chapters 1 and 2 are confusing

### ISSUE THREAD

**Issue by Markus1954** [markjprice/markjprice#1]
I am reading C# 11 and .NET 7. The first 2 chapters you use visual studio code and visual studio community. You have too much going on between the 2 ide's. Use only one to eliminate the confusion. It would be helpful to do so.

**Comment by markjprice** [comment]
In Chapter 1, I provide detailed instructions for both Visual Studio 2022 and Visual Studio Code. In the section, "Building console apps using Visual Studio 2022", on page 19, I say if you "want to use Visual Studio Code, then you can skip this section", and similarly in the Visual Studio Code section. So any reader who only wants to use one or the other can do so. 

In Chapter 2 onwards, I provide more general instructions that are not IDE-specific unless needed. I'm sorry that this confuses you but no-one else has complained so I won't be changing this approach any time soon.
